domain_path: /home/daniel/DigFInal/Digfinal/export/Digfinal/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/2025.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
